on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}